# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50ee75873572d7d1c829d2a374ebfba494961c952356831ecc811c74640cf6f3a5f10c78d208d8f0d5f8763bd51b6bca289cfab8373a1742edf0915352dd4bd0

test:
  secret_key_base: bbcf190e3456e54e8c419bf62a2189968e1fe9967ae9eabe4812b3d2667cdcf2b887141b4e5cb9c5f2b3a43e054b8923d5990c6487c75a543ff2de565d752742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
